Fix 7
aniishme/inventory-management-system pull request #8
Opened 2022-09-06 06:39 UTC by aniishme

#7 
- Endpoint to check user logged in, clear cookie if invalid
- zed validation fixed
- jwt sign payload updated
- cookie option updated

2022-09-08 10:13 UTC, GauravRajSharma requested changes

2022-09-08 10:13 UTC, GauravRajSharma commented on src/controllers/auth.controller.ts
> +    const cookieAge = 60 * 60 * 24 * 7;
try not use magic numbers like this. rather use
```ts
const ONE_WEEK = 60 * 60 * 24 * 7;
```

2022-09-12 14:40 UTC, aniishme reviewed
done

2022-09-13 14:45 UTC, GauravRajSharma approved these changes

2022-09-13 14:45 UTC, merged